export const routes = {
  login: '/login',
  overview: '/overview',
  funnel: '/funnel',
  revenue: '/revenue',
  matching: '/matching',
  chat: '/chat',
  chatConversations: '/chat-conversations',
  safety: '/safety',
  demographics: '/demographics',
  onboardingDropoff: '/onboarding-dropoff',
  retention: '/retention',
  lifeTogether: '/life-together',
  selfie: '/selfie',
  searchIndex: '/search-index',
  otp: '/otp',
  loginFunnel: '/login-funnel',
  otpUnverified: '/otp-unverified',
  likes: '/likes',
  users: '/users',
  userDetail: (userId: string) => `/users/${userId}`,
  reviewQueue: '/review-queue',
  reports: '/reports',
  reportDetail: (reportId: string) => `/reports/${reportId}`,
  sales: '/sales',
  salesFollowUps: '/sales/follow-ups',
  salesConversions: '/sales/conversions',
  salesPerformance: '/sales/performance',
  salesLeadDetail: (userId: string) => `/sales/${userId}`,
  vip: '/vip',
  vipFollowUps: '/vip/follow-ups',
  vipLeadDetail: (userId: string) => `/vip/${userId}`,
  deletedAccounts: '/deleted-accounts',
  deletedAccountsFollowUps: '/deleted-accounts/follow-ups',
  deletedAccountsConversions: '/deleted-accounts/conversions',
  deletedAccountsPerformance: '/deleted-accounts/performance',
  deletedAccountsLeadDetail: (userId: string) => `/deleted-accounts/${userId}`,
} as const
