export const routes = {
  login: '/login',
  overview: '/overview',
  funnel: '/funnel',
  revenue: '/revenue',
  matching: '/matching',
  chat: '/chat',
  safety: '/safety',
  demographics: '/demographics',
  retention: '/retention',
  lifeTogether: '/life-together',
  selfie: '/selfie',
  searchIndex: '/search-index',
  otp: '/otp',
  likes: '/likes',
  users: '/users',
  userDetail: (userId: string) => `/users/${userId}`,
  reports: '/reports',
  reportDetail: (reportId: string) => `/reports/${reportId}`,
  sales: '/sales',
  salesLeadDetail: (userId: string) => `/sales/${userId}`,
} as const
