export const ADMIN_API_BASE = '/api/admin'
export const GEO_API_BASE = '/api/geo'

export const adminEndpoints = {
  authToken: `${ADMIN_API_BASE}/auth/token`,
  authLogin: `${ADMIN_API_BASE}/auth/login`,
  analytics: {
    overview: `${ADMIN_API_BASE}/analytics/overview`,
    funnel: `${ADMIN_API_BASE}/analytics/funnel`,
    revenue: `${ADMIN_API_BASE}/analytics/revenue`,
    matching: `${ADMIN_API_BASE}/analytics/matching`,
    chat: `${ADMIN_API_BASE}/analytics/chat`,
    safety: `${ADMIN_API_BASE}/analytics/safety`,
    demographics: `${ADMIN_API_BASE}/analytics/demographics`,
    genderMonitoring: `${ADMIN_API_BASE}/analytics/gender-monitoring`,
    geoByGender: `${ADMIN_API_BASE}/analytics/geo-by-gender`,
    onboardingDropoffWithMedia: `${ADMIN_API_BASE}/analytics/onboarding-dropoff-with-media`,
    retention: `${ADMIN_API_BASE}/analytics/retention`,
    lifeTogether: `${ADMIN_API_BASE}/analytics/life-together`,
    lifeTogetherOnboarding: `${ADMIN_API_BASE}/analytics/life-together-onboarding`,
    selfie: `${ADMIN_API_BASE}/analytics/selfie`,
    searchIndex: `${ADMIN_API_BASE}/analytics/search-index`,
    otp: `${ADMIN_API_BASE}/analytics/otp`,
    loginFunnel: `${ADMIN_API_BASE}/analytics/login-funnel`,
    otpUnverified: `${ADMIN_API_BASE}/analytics/otp-unverified`,
    likes: `${ADMIN_API_BASE}/analytics/likes`,
  },
  geo: {
    countries: `${GEO_API_BASE}/countries`,
    states: `${GEO_API_BASE}/states`,
    cities: `${GEO_API_BASE}/cities`,
  },
  users: {
    search: `${ADMIN_API_BASE}/users/search`,
    detail: (userId: string) => `${ADMIN_API_BASE}/users/${userId}`,
    newlyJoined: `${ADMIN_API_BASE}/users/newly-joined`,
    profileRejected: `${ADMIN_API_BASE}/users/profile-rejected`,
    bioRejected: `${ADMIN_API_BASE}/users/bio-rejected`,
    deleted: `${ADMIN_API_BASE}/users/deleted`,
    reviewQueue: `${ADMIN_API_BASE}/users/review-queue`,
    forceApproveReview: (userId: string) => `${ADMIN_API_BASE}/users/${userId}/force-approve-review`,
  },
  reports: {
    list: `${ADMIN_API_BASE}/reports`,
    detail: (reportId: string) => `${ADMIN_API_BASE}/reports/${reportId}`,
  },
  chat: {
    conversations: `${ADMIN_API_BASE}/chat/conversations`,
    messages: (matchId: string) => `${ADMIN_API_BASE}/chat/conversations/${matchId}/messages`,
  },
  sales: {
    leads: `${ADMIN_API_BASE}/sales/leads`,
    detail: (userId: string) => `${ADMIN_API_BASE}/sales/leads/${userId}`,
    updateStatus: (userId: string) => `${ADMIN_API_BASE}/sales/leads/${userId}/status`,
    updateNote: (userId: string) => `${ADMIN_API_BASE}/sales/leads/${userId}/note`,
    updateFollowUp: (userId: string) => `${ADMIN_API_BASE}/sales/leads/${userId}/follow-up`,
    claim: (userId: string) => `${ADMIN_API_BASE}/sales/leads/${userId}/claim`,
    release: (userId: string) => `${ADMIN_API_BASE}/sales/leads/${userId}/release`,
    assign: (userId: string) => `${ADMIN_API_BASE}/sales/leads/${userId}/assign`,
    followUps: `${ADMIN_API_BASE}/sales/follow-ups`,
    activities: (userId: string) => `${ADMIN_API_BASE}/sales/leads/${userId}/activities`,
    communications: (userId: string) => `${ADMIN_API_BASE}/sales/leads/${userId}/communications`,
    conversions: `${ADMIN_API_BASE}/sales/conversions`,
    agentPerformance: `${ADMIN_API_BASE}/sales/agents/performance`,
    savedViews: `${ADMIN_API_BASE}/sales/saved-views`,
    savedView: (viewId: string) => `${ADMIN_API_BASE}/sales/saved-views/${viewId}`,
    summary: `${ADMIN_API_BASE}/sales/summary`,
  },
  salesDeleted: {
    leads: `${ADMIN_API_BASE}/sales/deleted/leads`,
    detail: (userId: string) => `${ADMIN_API_BASE}/sales/deleted/leads/${userId}`,
    updateStatus: (userId: string) => `${ADMIN_API_BASE}/sales/deleted/leads/${userId}/status`,
    updateNote: (userId: string) => `${ADMIN_API_BASE}/sales/deleted/leads/${userId}/note`,
    updateFollowUp: (userId: string) => `${ADMIN_API_BASE}/sales/deleted/leads/${userId}/follow-up`,
    claim: (userId: string) => `${ADMIN_API_BASE}/sales/deleted/leads/${userId}/claim`,
    release: (userId: string) => `${ADMIN_API_BASE}/sales/deleted/leads/${userId}/release`,
    assign: (userId: string) => `${ADMIN_API_BASE}/sales/deleted/leads/${userId}/assign`,
    followUps: `${ADMIN_API_BASE}/sales/deleted/follow-ups`,
    activities: (userId: string) => `${ADMIN_API_BASE}/sales/deleted/leads/${userId}/activities`,
    communications: (userId: string) => `${ADMIN_API_BASE}/sales/deleted/leads/${userId}/communications`,
    conversions: `${ADMIN_API_BASE}/sales/deleted/conversions`,
    agentPerformance: `${ADMIN_API_BASE}/sales/deleted/agents/performance`,
    savedViews: `${ADMIN_API_BASE}/sales/deleted/saved-views`,
    savedView: (viewId: string) => `${ADMIN_API_BASE}/sales/deleted/saved-views/${viewId}`,
    summary: `${ADMIN_API_BASE}/sales/deleted/summary`,
  },
  vip: {
    leads: `${ADMIN_API_BASE}/vip/leads`,
    detail: (userId: string) => `${ADMIN_API_BASE}/vip/leads/${userId}`,
    updateStatus: (userId: string) => `${ADMIN_API_BASE}/vip/leads/${userId}/status`,
    updateNote: (userId: string) => `${ADMIN_API_BASE}/vip/leads/${userId}/note`,
    updateFollowUp: (userId: string) => `${ADMIN_API_BASE}/vip/leads/${userId}/follow-up`,
    claim: (userId: string) => `${ADMIN_API_BASE}/vip/leads/${userId}/claim`,
    release: (userId: string) => `${ADMIN_API_BASE}/vip/leads/${userId}/release`,
    assign: (userId: string) => `${ADMIN_API_BASE}/vip/leads/${userId}/assign`,
    followUps: `${ADMIN_API_BASE}/vip/follow-ups`,
  },
} as const
